### ISSUE TITLE
Powershell Works Amazing

### ISSUE THREAD

**Issue by molochworship** [PietJankbal/powershell-wrapper-for-wine#10]
So I got powershell working with your script and I just am encountering one more error

When I go to open the waves plugins with linvst the dialog window that allows you to select the plugins does not appear do you know how to fix this issue?

Other than that waves is 100% working with this script and thank you so much for making it.

**Comment by PietJankbal** [comment]
Could you post the console output while you try to open the dialog window?

**Comment by PietJankbal** [comment]
Hi, as there isn`t response i`ll close this one. Feel free to reopen if you have more info

Regards
