### ISSUE TITLE
wine powershell seems faild.

### ISSUE THREAD

**Issue by wastee** [PietJankbal/powershell-wrapper-for-wine#16]
## Install step

1. create a new clean 64bit wineprefix
1. wget https://github.com/PietJankbal/powershell-wrapper-for-wine/raw/master/install_pwshwrapper.exe
1. wine install_pwshwrapper.exe
2. wine powershell, in the same wineprefix and folder
3. then shows the Install log

## Install log

```
❯ wine powershell
fsync: up and running.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 7.0-rc4 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
0108:fixme:imm:ImeSetActiveContext (0x7594d0, 1): stub
0108:fixme:imm:ImmReleaseContext (0001006C, 007594D0): stub
00c4:fixme:imm:ImeSetActiveContext (0x263940, 0): stub
00c4:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000263940): stub

Downloading PowerShell-7.0.3-win-x64.msi

0108:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0108:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3

Downloading install2.ps1

0108:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
011c:fixme:file:NtLockFile I/O completion on lock not implemented yet
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
011c:err:mscoree:LoadLibraryShim error reading registry key for installroot
011c:err:mscoree:LoadLibraryShim error reading registry key for installroot
011c:err:mscoree:LoadLibraryShim error reading registry key for installroot
011c:err:mscoree:LoadLibraryShim error reading registry key for installroot
0140:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019EF98
0140:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\PowerShell\\7\\mscordaccore.dll", 0000000000DC0000) stub
0140:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 4 0000000000244B68 000000000019A828 000000000019B570 0000000000000000
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 0000000000244B40 000000000019B488 000000000019C1D0 0000000000000000
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 0000000000244B40 000000000019B488 000000000019C1D0 0000000000000000
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 0000000000256D10 000000000019B938 000000000019C680 0000000000000000
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 0000000000256D10 000000000019C598 000000000019D2E0 0000000000000000
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 0000000000256D10 000000000019C598 000000000019D2E0 0000000000000000
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017EABB8, 34) stub
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017EA8B8, 17) stub
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 00000000002AF448 000000000019B588 000000000019C2D0 0000000000000000
0140:fixme:combase:RoGetActivationFactory (L"Windows.Foundation.Diagnostics.AsyncCausalityTracer", {50850b26-267e-451b-a890-ab6a370245ee}, 000000000019D298): semi-stub
0140:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017EB3E8, 40) stub
0140:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 00000000002B0848 000000000019A7D8 000000000019B520 0000000000000000
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017EBB28, 51) stub
015c:fixme:sync:SetWaitableTimerEx (00000000000001A0, 000000001A9FFDA8, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
0140:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0160:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 0000000000000000 000000001AB9F1F8) returning a dummy value (current locale)
0160:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 00000000017F08A8 000000001AB9F1F8) returning a dummy value (current locale)
0140:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E888: stub
0158:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0158:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\PowerShell\\7\\pwsh.exe_7.0.3 SHA: b08a8ad3da59a0cddf3351feea57d650eb6c41db", 000000001A617630
0158:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A617638
0160:fixme:virtual:NtFlushProcessWriteBuffers stub
0164:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0168:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0158:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0170:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
```

![图片](https://user-images.githubusercontent.com/22229962/148343190-39ac6eab-5050-4188-92c4-cb2822b8886f.png)

## What i tried

My network sometime can not connect github. So i try to run wine install_pwshwrapper.exe under **proxychains** or **http_proxy**, but also stuck like above.

I can confirm either proxychains or http_proxy setup correctly.

But i get same result either under proxy or not.

## My system info

|        | version                                                  |
| ------ | -------------------------------------------------------- |
| Kernel | 5.15.13-xanmod-tt                                        |
| WINE   | wine-7.0-rc4-28-g9ef5c9c0090 ( TkG Staging Esync Fsync ) |

**Comment by PietJankbal** [comment]
Hi,

Strange, it works for me with Staging 7.0rc4

It seems to hang just before Conemu should be installed. The lines below should show up. Maybe another connection problem , to Conemu site https://conemu.github.io/?

Any chance you could try without those 'proxy' things?

019c:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
01e4:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000032E3378, 40) stub
01e4:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000032E56A0, 30) stub
01e4:fixme:advapi:SaferIdentifyLevel (1 0000000020BEEA88 0000000020BEEBF0 0000000002F242DC) stub
01e4:fixme:advapi:SaferComputeTokenFromLevel (00000000DEADBEEF, 0000000000000000, 0000000020BEEBE8, 1, 0000000000000000) stub
01e4:fixme:advapi:SaferCloseLevel (00000000DEADBEEF) stub
01e4:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001BD27638
01e4:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000003304A94, 14354, L"C:\\users\\louis\\Temp\\install2.ps1", 00000000DEADBEEF, 0000000020BEEBA8
01e4:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
Download latest version information
   from https://conemu.github.io/version.ini

**Comment by wastee** [comment]
Thank's your information.

I CAN connect "conemu.github.io" without proxy, but CAN NOT connect "https://github.com/xxx/xxx/releases/download" without proxy.

Maybe there are some bug in running ps1 with proxy. Normally proxychains or http_proxy will work fine in WINE such as winetricks .

I'll try to replace these url and compile myself. Then share what i found at the end.

Thank you.

**Comment by wastee** [comment]
Seems not network issues. I change & uplode all files to my own server, include conemu's ps1 file. I still stuck like above.

So i add some fwprintf line in `main.c`, compile it.

Then find out the location i stuck.

-----------

> main c Code
```
CreateProcessW(lstrcatW( msiexecW, L"\\msiexec.exe" ), lstrcatW(  lstrcatW( bufW, lstrcatW( tmpW, L"PowerShell-7.0.3-win-x64.msi") ), L" /q") , 0, 0, 0, 0, 0, 0, &si, &pi);

[PRINT SOMETHING]

WaitForSingleObject( pi.hProcess, INFINITE ); CloseHandle( pi.hProcess ); CloseHandle( pi.hThread );
```

Seems i stuck in `WaitForSingleObject` line. But i don't know why.

---
> terminal output

```
[PRINT SOMETHING]
011c:fixme:file:NtLockFile I/O completion on lock not implemented yet
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0140:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019EF98
0140:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\PowerShell\\7\\mscordaccore.dll", 0000000000DC0000) stub
0140:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017CABB8, 34) stub
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017CA8B8, 17) stub
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017CB3E8, 40) stub
015c:fixme:sync:SetWaitableTimerEx (00000000000001A4, 000000001A9FFDA8, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
0140:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0160:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 0000000000000000 000000001AB9F1F8) returning a dummy value (current locale)
0160:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 00000000017D08A8 000000001AB9F1F8) returning a dummy value (current locale)
0140:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E888: stub
0158:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0158:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\PowerShell\\7\\pwsh.exe_7.0.3 SHA: b08a8ad3da59a0cddf3351feea57d650eb6c41db", 000000001A617630
0158:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A617638
0160:fixme:virtual:NtFlushProcessWriteBuffers stub
0164:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0168:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet
0158:fixme:thread:NtQueryInformationThread ThreadIsIoPending info class not supported yet



```

**Comment by PietJankbal** [comment]
huh, strange yeah. Somehow the msiexec then apparently never stops/hangs. I haven`t got a clue why really. The only thing i can now think of is try a complete manual install and see if that works:
- Manual  install powershell from
 https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x64.msi
- Then install Conemu: wget https://conemu.github.io/install2.ps1
and 'wine pwsh.exe -f install2.ps1'
- and install the powershell wrapper files:
cp -rf ./powershell64.exe ~/.wine/drive_c/windows/system32/WindowsPowerShell/v1.0/powershell.exe

cp -rf ./powershell32.exe ~/.wine/drive_c/windows/syswow64/WindowsPowerShell/v1.0/powershell.exe

Then if you run 'wine powershell' , does that work? If it works there might be a problem with my script, but as I said, I haven`t got a clue what. P.S.: I guess you don`t have any native dlls installed? Preferably test on a complete new fresh WINEPREFIX (e.g. ~/.winetest)
Regards

**Comment by wastee** [comment]
I think there's no issue in your script, manual install still hangs.

## 1st step

I hangs in 1st step in the begning. `PowerShell-7.0.3-win-x64.msi` install success **until i uncheck this checkbox**:

I have to uncheck this to make install complete.

![CopyQ zfJYHe](https://user-images.githubusercontent.com/22229962/148484679-a7c1fe36-cb1d-48be-bdc9-df4d8a4b859e.png)

ps: I dont know if this checkbox important. But if it checked, `PowerShell-7.0.3-win-x64.msi` install will hang.

**If i run `wine pwsh.exe` after this step. pwsh.exe will hangs like 2rd step**

**I think maybe there's some issues in install PowerShell-7.0.3-win-x64.msi**

## 2rd step

Then i hangs in 2rd step `wine pwsh.exe -f install2.ps1`. 

It show simmilar output like i post at first time.

```
❯ wine pwsh.exe -f install2.ps1
fsync: up and running.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 7.0-rc4 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0108:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019EF98
0108:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\PowerShell\\7\\mscordaccore.dll", 0000000000DC0000) stub
0108:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017DA9C8, 34) stub
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017DA6C8, 17) stub
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017DB1F8, 40) stub
0124:fixme:sync:SetWaitableTimerEx (0000000000000198, 000000001A9FFDA8, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
0108:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0128:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 0000000000000000 000000001AB9F1F8) returning a dummy value (current locale)
0128:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AB9F200 00000000017E08A8 000000001AB9F1F8) returning a dummy value (current locale)
0108:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E888: stub
0120:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0120:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\PowerShell\\7\\pwsh.exe_7.0.3 SHA: b08a8ad3da59a0cddf3351feea57d650eb6c41db", 000000001A617630
0120:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A617638
0108:fixme:virtual:NtFlushProcessWriteBuffers stub
```

------

And no, i have no native dlls installed.

**I also try a fresh install guest OS(Manjaro) in virtualbox, install wine-7.0-rc2 (Staging).
Hangs in same step like in my HOST system.**

Thanks for your time! I will keep looking if what i miss or WINE fix.

**Comment by wastee** [comment]
## Another test

I run an x server and desktop in my server running Debian 10. Install wine-staging 7.0 rc4.
Script works fine! ConEmu pop out in Debian 10 remote server.

Transfer the wine folder to my local machine. Run the same command `wine powershell` , pop out ConEmu too.
But something different, very strange. 

Does any chance some network connection issuse cause pwsh.exe strange?

Or any chance language setup cause pwsh.exe strange?

## Test result 

WINE | Distro | result
-- | -- | --
wine-staging 7.0 rc2 | Manjaro (local virtualbox) | FAILED
wine-staging 7.0 rc4 / wine-staging 7.0 rc4 | Archlinux (local) | FAILED
wine-staging 7.0 rc4 | Debian 10 (remote) | SUCCESSED
Debian 10’s success wine folder + wine-staging 7.0 rc4 | Archlinux (local) |FAILED
wine-staging 7.0 rc4 | Ubuntu 20.04 (local) | FAILED

### remote Debian 10

![图片](https://user-images.githubusercontent.com/22229962/148509278-740a2008-0c6c-4859-b71c-3f430b7b026a.png)


### local Archlinux

![图片](https://user-images.githubusercontent.com/22229962/148509353-88deb374-1ea6-4989-8964-b9bdd503f9cc.png)

**Comment by wastee** [comment]
Finally! I finally find out what cause these issues!

I run success with `LC_ALL=en_US.UTF-8` wine
I failed at first because all my local system include virtualbox running in `LANG=zh_CN.UTF-8`
Hope this information will help other non-English users.

Now i can login Waves Central.
Thank's your time and help!

![图片](https://user-images.githubusercontent.com/22229962/148520831-1bc92836-448d-4da8-accd-667933ea6bb3.png)

**Comment by PietJankbal** [comment]
Hi wastee,

Thanks for your efforts tracking this cause down. I can confirm same thing happens here when i run with LC_ALL=zh_CN.UTF-8. I suspect it`s a bug in wine. I opened a bugreport at wine, maybe  somehow it gets fixed in future wine-releases when someone knows solution. 
Regards
