### ISSUE TITLE
Getting "Something went wrong :( (32-bit?, winversion <win7?, failing download? ...." on clean install of Wine - Arch Linux

### ISSUE THREAD

**Issue by fizzipop22** [PietJankbal/powershell-wrapper-for-wine#17]
![Screenshot from 2022-01-07 21-56-49](https://user-images.githubusercontent.com/97306351/148646031-a9c29d4c-8a9e-43dd-8b4e-c794eaaacc06.png)

Tried changing to different Windows Versions etc.

**Comment by PietJankbal** [comment]
Hi, I guess it cannot download the files because of the errors you see: Failed to load libgnutls

Not sure what system you are on but on Debian i would try:
sudo apt-get install libgnutls30 libgnutls30:i386

And also that error ntlm_auth not found is not good, try fix with sudo apt-get install winbind

If you`re on other system i guess you need other commands to install

**Comment by fizzipop22** [comment]
I’m on arch but I’ll try and get them installed

**Comment by fizzipop22** [comment]
@PietJankbal I'm now getting this error, after installing winbind and libgnutls

`0100:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0100:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3
`

**Comment by fizzipop22** [comment]
I've changing directory into drive_c/Program Files/Waves Central, and running "wine Waves Central.exe" from there, still getting errors however. I get a window saying "The program Waves Central has encountered a serious problem and needs to close." However, Powershell still actually loads up. I'll attach the winedbg log at the end.

Here's the terminal log:

`002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0-rc4 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0100:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,000000000011FD00,000000000011FCF8) stub!
0104:fixme:process:NtQueryInformationProcess (0xffffffffffffffff,info_class=49,0xe6fc20,0x00000008,(nil)) Unknown information class
0100:fixme:heap:RtlSetHeapInformation 0000000000000000 1 0000000000000000 0 stub

0100:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011F684, 0000000000000000 000000000011F680
0100:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011F684 0000000000000000 000000000011F680) returning a dummy value (current locale)
0100:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011F684, 000000000011F660 000000000011F680
0100:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011F684 000000000011F660 000000000011F680) returning a dummy value (current locale)
0100:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
011c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000296FE10
0100:fixme:iphlpapi:GetBestRoute2 (0000000002FD83A0, 0, 0000000000000000, 0000000002FD85A0, 0x00000000, 000000000011C838, 000000000011C818): stub
0100:fixme:msg:ChangeWindowMessageFilterEx 0000000000010066 4a 1 0000000000000000
0100:fixme:winsock:WSALookupServiceBeginW (000000000011F2C0 0x00000ff0 000000000011F338) Stub!
0100:fixme:iphlpapi:NotifyAddrChange (Handle 000000000011F468, overlapped 00000000033B8820): stub
0100:fixme:win:GetPointerDevices (000000000011EE2C 0000000000000000): partial stub
0100:fixme:system:DisplayConfigGetDeviceInfo Unimplemented packet type: 11
0130:fixme:wtsapi:WTSRegisterSessionNotification Stub 0000000000010068 0x00000001
0148:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
0148:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
0148:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
0148:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
0148:fixme:sync:NtSetInformationJobObject stub: 0x304 4 0x3e6ed78 4
0100:fixme:service:I_ScRegisterDeviceNotification Notification filters are not yet implemented.
18:13:27 [critical] MainInitialization::init starts
0148:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
0154:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,000000000011FD00,000000000011FCF8) stub!
0154:fixme:heap:RtlSetHeapInformation 0000000000000000 1 0000000000000000 0 stub
0154:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0184:fixme:thread: QueryThreadCycleTime (0000000000000140,00000000019CFBF0): stub!
0180:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019EF98
0180:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\Powershell\\7\\mscordaccore.dll", 0000000000D40000) stub
0180:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174ABA8, 34) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174A8A8, 17) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174B3D8, 40) stub
01a0:fixme:sync:SetWaitableTimerEx (0000000000000190, 000000001A86FDA8, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
0180:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
01a8:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001ABAF200 0000000000000000 000000001ABAF1F8) returning a dummy value (current locale)
01a8:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001ABAF200 00000000017508A8 000000001ABAF1F8) returning a dummy value (current locale)
0154:fixme:winediag:wined3d_select_feature_level None of the requested D3D feature levels is supported on this GPU with the current shader backend.
0180:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E888: stub
0180:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
019c:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
019c:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\Powershell\\7\\pwsh.exe_7.0.3 SHA: b08a8ad3da59a0cddf3351feea57d650eb6c41db", 000000001A597630
019c:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A597638
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001767798, 38) stub
0180:fixme:ntdll:NtQuerySystemInformation (0x000000ce,0x19bca8,0x00000008,(nil)) stub
0180:fixme:nls:GetCalendarInfoW Unimplemented caltype 2
0180:fixme:nls:GetCalendarInfoW Unimplemented caltype 4
0180:fixme:nls:GetCalendarInfoW Unimplemented caltype 57
wine: Unhandled page fault on read access to 0000000000000000 at address 00007F74A0FDA043 (thread 0154), starting debugger...
0180:fixme:advapi:SaferIdentifyLevel (1 000000000019D058 000000000019D1C0 00000000017941A4) stub
0180:fixme:advapi:SaferComputeTokenFromLevel (00000000DEADBEEF, 0000000000000000, 000000000019D1B8, 1, 0000000000000000) stub
0180:fixme:advapi:SaferCloseLevel (00000000DEADBEEF) stub
01c8:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000180F330, 37) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001820778, 38) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000018214E0, 37) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000182B130, 33) stub
0180:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
0180:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
0180:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000018701D8, 46) stub
0180:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001894590, 65) stub
01a4:fixme:virtual:NtFlushProcessWriteBuffers stub
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0180:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
01f0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001B6B2D8, 30) stub
01f0:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A597638
01b8:fixme:imm:ImeSetActiveContext (0x2548d0, 1): stub
01b8:fixme:imm:ImmReleaseContext (00000000000100DE, 00000000002548D0): stub
01f0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001B6780C, 90, L"", 00000000DEADBEEF, 000000001F8FECE8
01d0:fixme:imm:ImeSetActiveContext (0x2565d0, 0): stub
01d0:fixme:imm:ImmReleaseContext (000000000005009A, 00000000002565D0): stub
01f0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001B7D698, 40) stub
01f0:fixme:advapi:SaferIdentifyLevel (1 000000001F8FE498 000000001F8FE600 00000000017941A4) stub
01f0:fixme:advapi:SaferComputeTokenFromLevel (00000000DEADBEEF, 0000000000000000, 000000001F8FE5F8, 1, 0000000000000000) stub
01f0:fixme:advapi:SaferCloseLevel (00000000DEADBEEF) stub
01f0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001BBFBF4, 6412, L"C:\\Program Files\\Powershell\\7\\profile.ps1", 00000000DEADBEEF, 000000001F8FE5B8
01f0:fixme:file:NtLockFile I/O completion on lock not implemented yet
01f0:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
01f0:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A597638
01f0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 00000000017F831C, 160, L"", 00000000DEADBEEF, 000000001F8FECE8
01f0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001E586BC, 158, L"", 00000000DEADBEEF, 000000001F8FE728
0180:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
01f0:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A597638
01f0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001821A3C, 18, L"", 00000000DEADBEEF, 000000001F8FECE8
0180:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
0180:fixme:amsi:AmsiUninitialize 00000000DEADBEEF
18:13:32 [info]     NodeOSService:: {
  osType: 1,
  quitRelaunchBehaviour: { quitOrRelaunchRequestBridge: {} },
  newLineSeparator: '\r\n',
  homePath: 'C:\\users\\fizzipop22',
  computerName: 'vmware',
  appDataPath: 'C:\\users\\fizzipop22\\AppData\\Roaming',
  appPath: 'C:\\Program Files\\Waves Central\\resources\\app.asar',
  internalCachePath: 'C:\\users\\fizzipop22\\AppData\\Roaming\\Waves Centra
l',
  documentsPath: 'C:\\users\\fizzipop22\\Documents',
  desktopPath: 'C:\\users\\fizzipop22\\Desktop',
  externalResourcesPath: 'C:\\Program Files\\Waves Central\\resources\\res\
\external',
  osName: 'Windows',
  wavesSharedDataPath: 'C:\\ProgramData\\Waves Audio',
  wavesUserCachePath: 'C:\\users\\fizzipop22\\AppData\\Local\\Waves Audio'
,
  wavesSoftwareRootPath: 'C:\\Program Files (x86)\\Waves',
  wavesDataPath: 'C:\\Program Files (x86)\\Waves\\Data',
  wavesPreferencePath: 'C:\\users\\fizzipop22\\AppData\\Roaming\\Waves Audi
o\\Preferences',
  osArchitecture: 0,
  shellVersion: { major: 7, minor: 0, fix: 0, revi
sion: 0 },
  rebootHelper: {},
  getSizeBehaviour: {},
  osVersion: { major: 7, minor: 0, fix: 0, revisio
n: 0 },
  cpuModel: 'Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz',
  dumpPath: 'C:\\users\\fizzipop22\\AppData\\Roaming\\Waves Audio\\Waves Ce
ntral\\Logs',
  userInfo: {
    uid: -1,
    gid: -1,
    username: 'fizzipop22',
    homedir: 'C:\\users\\fizzipop22',
    shell: null
  },
  osSupported: true
}
020c:fixme:where:wmain stub: L"where" L"powershell.exe"
18:13:32 [verbose]  ElectronWindowsInitializerValidator::validate powe
rshell location { stdout: '', stderr: '' }
18:13:33 [warning]  ElectronWindowsInitializerValidator::validate runn
ing in admin mode
18:13:33 [warning]  WinNodeDisk:getFreeSpaceGB failed for current meth
od wmic wmic logicaldisk where "DeviceID='C:'" get FreeSpace
18:13:33 [warning]  WinNodeDisk:getFreeSpaceGB failed for current meth
od wmicAbsolutePath wmic logicaldisk where "DeviceID='C:'" get FreeSpace
18:13:34 [warning]  WinNodeDisk:getFreeSpaceGB failed for current meth
od powershell "%SystemRoot%\System32\Wbem\wmic.exe" logicaldisk where DeviceID='
C:' get FreeSpace
0264:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000019EF98
0264:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files\\Powershell\\7\\mscordaccore.dll", 0000000000D40000) stub
0264:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0280:fixme:sync:SetWaitableTimerEx (0000000000000180, 000000001A75FDA8, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174AA28, 34) stub
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174A728, 17) stub
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000174B258, 40) stub
0264:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0284:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AA0F200 0000000000000000 000000001AA0F1F8) returning a dummy value (current locale)
0284:fixme:nls:get_dummy_preferred_ui_language (0x8 000000001AA0F200 00000000017508A8 000000001AA0F1F8) returning a dummy value (current locale)
0264:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E888: stub
0264:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
027c:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
027c:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\Powershell\\7\\pwsh.exe_7.0.3 SHA: b08a8ad3da59a0cddf3351feea57d650eb6c41db", 000000001A857630
027c:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A857638
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000017676C0, 38) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:ntdll:NtQuerySystemInformation (0x000000ce,0x19bca8,0x00000008,(nil)) stub
0264:fixme:nls:GetCalendarInfoW Unimplemented caltype 2
0264:fixme:nls:GetCalendarInfoW Unimplemented caltype 4
0264:fixme:nls:GetCalendarInfoW Unimplemented caltype 57
0264:fixme:advapi:SaferIdentifyLevel (1 000000000019D058 000000000019D1C0 0000000001796BF4) stub
0264:fixme:advapi:SaferComputeTokenFromLevel (00000000DEADBEEF, 0000000000000000, 000000000019D1B8, 1, 0000000000000000) stub
0264:fixme:advapi:SaferCloseLevel (00000000DEADBEEF) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0298:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001811330, 37) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001820FD8, 38) stub
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001821D40, 37) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000182B990, 33) stub
0264:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
0264:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
0264:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 000000000019B2B0, 000000000019B060, 000000000019B2B8, 000000000019B2A8
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000186F870, 46) stub
0264:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001894170, 65) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0288:fixme:virtual:NtFlushProcessWriteBuffers stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
0264:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
02b0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001B672A8, 30) stub
02b0:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 000000001A857638
02b0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001B64664, 90, L"", 00000000DEADBEEF, 000000001F70EC68
02b0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000001B79668, 40) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
02b0:fixme:advapi:SaferIdentifyLevel (1 000000001F70E418 000000001F70E580 0000000001796BF4) stub
02b0:fixme:advapi:SaferComputeTokenFromLevel (00000000DEADBEEF, 0000000000000000, 000000001F70E578, 1, 0000000000000000) stub
02b0:fixme:advapi:SaferCloseLevel (00000000DEADBEEF) stub
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
02b0:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000001BBBD04, 6412, L"C:\\Program Files\\Powershell\\7\\profile.ps1", 00000000DEADBEEF, 000000001F70E538
02b0:fixme:file:NtLockFile I/O completion on lock not implemented yet
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
18:13:37 [warning]  WinNodeDisk::getFreeSpaceGB timeout, will use sync
 method instead
02b0:fixme:amsi:AmsiCloseSession 00000000DEADBEEF, 00000000DEADBEEF
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b8:fixme:dbghelp:elf_search_auxv can't find symbol in module`

**Comment by PietJankbal** [comment]
hmm, actually i haven`t got a clue where that crash comes from; maybe d3d related?

Does run by : WINEDLLOVERRIDES=libglesv2=d wine Waves\ Central.exe

change anything?

**Comment by fizzipop22** [comment]
Thanks, that worked perfectly. Get a black screen but throwing the Window around fixes that. If I have problems with other VSTs unrelated to Waves, am I free to contact you? I really want  a reason to ditch Windows and produce + game on Linux, and I havent been on Linux for over 7 years now.

**Comment by PietJankbal** [comment]
Hi, nice that it worked, but it also shows your wine-setup is still not 100% right. You`re now running without GPU hardware acceleration (by disabling libglesv2), so I guess you should really install some graphics drivers (nvidia/ mesa) ( I don`t know much about that either) to have d3d support in wine. Maybe ask on some Arch forum?
While running Waves you should really see lots of dxgi and d3d fixme's in the console, then you know d3d hardware acceleration is enabled. Anyway , feel free to ask if you run into issues, though I`m not an expert ;)
Regards

**Comment by fizzipop22** [comment]
I’m using Linux on VMware right now and have VMWare tools enabled, so no drivers needed right?

**Comment by PietJankbal** [comment]
Oh i see, i don`t know anything about vmware , but i guess just as in VirtualBox you won`t have any d3d acceleration (?), at least I think wine doesn`t support that.
 AFAIK wine needs 'real' drivers, but maybe I`m talking bollocks, Anyway, you can still test without d3d accelaration, it will just be quite slower I guess

**Comment by fizzipop22** [comment]
Thank you :3

**Comment by SunflowerHunter** [comment]
Installing the lib32 version of gnutl on arch fixed the problem for me btw
