### ISSUE TITLE
Waves Central - Ver. 13.2.4 - Central has encountered a system permissions Issue 

### ISSUE THREAD

**Issue by Whitefrostyofficial** [PietJankbal/powershell-wrapper-for-wine#18]
So it's been a week, and I've been trying to fix my "Waves Central - Ver. 13.2.4" I've tried everything but nothing works and Waves Central just says
"fixing permission and ownership

Central has encountered a system permissions issue.

Any idea? I'd really appreciate it

I don't know what and I can't up upgrade my plugins

**Comment by PietJankbal** [comment]
Hi, make sure you use wine-staging, not "regular" wine.

BTW, this issue ("fixing permission and ownership") should be fixed in upcoming wine-7.14, which i think will be released in a week or so. 
Regards

**Comment by Whitefrostyofficial** [comment]
What's Wine-staging

And, oh ok

**Comment by PietJankbal** [comment]
Hi, wine-staging is kind of fork of regular wine, that contains experimental patches. But maybe easier to just wait for upcoming wine-7.14

regards

**Comment by Whitefrostyofficial** [comment]
Well im running on windows 11 so idk if wine-staging will work

But where I download that at is there a website for that or???

**Comment by PietJankbal** [comment]
Hi, if you run on windows 11 than you`re not at the right place here (you`re saying you are not running under wine at all, right?). 

This powershell-wrapper on this site is for running Waves on Linux  under wine (or wine-staging).

**Comment by GlennMm** [comment]
@PietJankbal  Hie i am on wine-staging-8.1. im still getting the system permission issue

**Comment by PietJankbal** [comment]
Hi, assuming this was invalid, and there's no update for about half a year so clsing this issue.

If you still think it's valid please reopen and provide updated info.

Regards

**Comment by PietJankbal** [comment]
Hi, assuming this was invalid, and there's no update for about half a year so clsing this issue.

If you still think it's valid please reopen and provide updated info.

Regards

**Comment by PietJankbal** [comment]
Hi, assuming this was invalid, and there's no update for about half a year so clsing this issue.

If you still think it's valid please reopen and provide updated info.

Regards
