### ISSUE TITLE
Waves Central won't open when wine is set to windows 10

### ISSUE THREAD

**Issue by niculw** [PietJankbal/powershell-wrapper-for-wine#2]
Hi again,
I know this is unrelated but was hoping you could help.
When running Waves Central under windows 10 i get the following error
```
16:19:58 [warning]  WinNodeDisk::parseOutput not output to parse
16:19:58 [critical] MainInitialization::init validator ElectronWindowsInitializerValidator returned
 fail
16:19:58 [critical] Main:init has failed to initialize Waves Central cannot detect the free space o
n your OS drive. Therefore, it cannot install software or manage licenses.

This may be because:

1. An antivirus is blocking Waves Central from accessing Windows Management Interface (WMI). Please disable y
our antivirus software and try running Waves Central again.

2. You do not have sufficient privileges to access WMI services. Please try another Administrator account in 
order to run Waves Central as an Admin, or contact your machine's Admin.

3. Your WMI Repository is missing or corrupted. Try to run Windows repair, or contact your machine's Admin.
```
How ever running it with a win7, 8, 8.1 machine it works completely fine. I must be missing a dll or something i think, but googling the error returns nothing. Any ideas?

**Comment by PietJankbal** [comment]
Hi,

I tried this and got the same error as you.
Looks like a missing API from ntdll. With the patch below I was able to start it in win10 mode up to the login-window
Just got the hint by starting "wine powershell", then it complains about this missing function.
I`ll try to get patch into wine later

diff --git a/dlls/ntdll/ntdll.spec b/dlls/ntdll/ntdll.spec
index ca427c46c04..4153fb21449 100644
--- a/dlls/ntdll/ntdll.spec
+++ b/dlls/ntdll/ntdll.spec
@@ -892,6 +892,7 @@
 @ stdcall RtlQueryPackageIdentity(long ptr ptr ptr ptr ptr)
 @ stdcall RtlQueryPerformanceCounter(ptr)
 @ stdcall RtlQueryPerformanceFrequency(ptr)
+@ stdcall RtlQueryProcessPlaceholderCompatibilityMode()
 @ stub RtlQueryProcessBackTraceInformation
 @ stdcall RtlQueryProcessDebugInformation(long long ptr)
 @ stub RtlQueryProcessHeapInformation
diff --git a/dlls/ntdll/rtl.c b/dlls/ntdll/rtl.c
index ca4fea84209..de3331fc63f 100644
--- a/dlls/ntdll/rtl.c
+++ b/dlls/ntdll/rtl.c
@@ -2145,3 +2145,8 @@ NTSTATUS WINAPI RtlQueryPackageIdentity(HANDLE token, WCHAR *fullname, SIZE_T *f
     FIXME("(%p, %p, %p, %p, %p, %p): stub\n", token, fullname, fullname_size, appid, appid_size, packaged);
     return STATUS_NOT_FOUND;
 }
+
+NTSTATUS WINAPI RtlQueryProcessPlaceholderCompatibilityMode(void)
+{
+return -2;
+}

**Comment by PietJankbal** [comment]
This issue should be fixed in most recent Staging version (wine-staging-6.0rc3)

**Comment by Hakazaba** [comment]
Hi, where is ntdll? I don't want to change wine versions
Edit: Ive found it, but i don't have the tools to edit the file.

**Comment by PietJankbal** [comment]
> Hi, where is ntdll? I don't want to change wine versions
> Edit: Ive found it, but i don't have the tools to edit the file.

Hi, just use (recent) Wine-Staging (instead of regular Wine) and it should be fine.

The 2nd comment refers to the case you would be willing to compile wine yourself, but then you`d have to download wine`s source code and have the knowledge how to compile wine. In case that`s the case: the affected code is in /dlls/ntdll/rtl.c b/dlls/ntdll/rtl.c and /dlls/ntdll/rtl.c b/dlls/ntdll/ntdll.spec

Regards

**Comment by Hakazaba** [comment]
Ah, im just kind of worried to change anything because im, using 64 bit wine to run vsts and i dont want to break everything again.

**Comment by Hakazaba** [comment]
I've installed wine-staging and waves central cannot access powershell. I have rerun he powershell wrapper scripts

**Comment by EchoL0t** [comment]
May be somebody knows how to fix this issue? (wine-staging 6.2, after switch to windows10)
```
00cc:fixme:ntdll:EtwRegisterTraceGuidsW (00000000008D9AF8, 0000000000A46B18, {04c6e16d-b99f-4a3a-9b3e-b8325bbc781e}, 1, 000000000031F460, (null), (null), 0000000000A46B20): stub
00cc:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {04c6e16d-b99f-4a3a-9b3e-b8325bbc781e}
00cc:fixme:svchost:AddServiceElem library L"C:\\windows\\system32\\WsmSvc.dll" expects undocumented SvchostPushServiceGlobals function to be called
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"WinRM" failed to start: 1053

```

**Comment by PietJankbal** [comment]
Hi EchoLot, do those fixme`s produce an error while trying run Waves? Otherwise I expect thpse fixme`s to be quite harmless

**Comment by EchoL0t** [comment]
@PietJankbal  Yep, I'm trying to run waves 12. I've successfully installed and ran waves 12 under win7, but need win10 to run plugins.
Done just manual fixes adding your powershell and `cp where.exe instl.exe`

**Comment by PietJankbal** [comment]
That "copy  where.exe instl.exe" causes issues, better avoid that i think . If you run into "permissions issues"  better try comment 10 from https://github.com/PietJankbal/powershell-wrapper-for-wine/issues/4

I`m trying to get a patch in Staging for fixing this bug, 

And for win10 you1ll need wine-staging; wine itsself will crash if windows version is set to 10 , staging has a patch for that

**Comment by EchoL0t** [comment]
Ok, thanks)  I'll better wait for a new version of wine-staging with your patch. Unfortunately I don't know how to build it in a proper way with support of all nessesary things like vulkan

**Comment by PietJankbal** [comment]
This "Central has encountered a system permissions issue"  error should be fixed by a yesterday`s  commit to  Wine-Staging, so in upcoming Wine-Staging-6.4 (next week) this issue should be gone.

**Comment by PietJankbal** [comment]
Closing this one, for subsequent issues please open new bugreports
