### ISSUE TITLE
Wine powershell fails after running the wrapper installer

### ISSUE THREAD

**Issue by KodzghlyCZ** [PietJankbal/powershell-wrapper-for-wine#22]
I've tried to download and run the wrapper installer. I got no error and got prompted to run 'wine pwershell'. However after running it, I got this output:

`002c:fixme:winediag:LdrInitializeThunk wine-staging 7.22 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0110:fixme:imm:ImeSetActiveContext (00010072, 1): stub
0110:fixme:imm:ImmReleaseContext (00010080, 00010072): stub
009c:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
009c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub

Downloading PowerShell-7.0.3-win-x64.msi

0110:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0110:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3

Downloading install2.ps1

0110:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0120:fixme:file:NtLockFile I/O completion on lock not implemented yet
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0120:err:msi:ITERATE_Actions Execution halted, action L"LaunchConditions" returned 1603

Downloading profile.ps1

0110:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0110:fixme:urlmon:DownloadBSC_OnStopBinding CopyFile failed: 3
0110:err:msvcrt:_invalid_parameter (null):0 (null): (null) 0`

And it doesn't seem to do anything.
I'm using wine staging 7.22, even tried with regular one, same effect.

All I'm getting is this window whenever I run it:

![image](https://user-images.githubusercontent.com/17799426/216311370-c89a4133-ae94-4bf3-a2c7-ded8ef6ba1bc.png)

**Comment by KodzghlyCZ** [comment]
I somehow solved the issue, but have no clue how. I installed the PowerShell myself and now at least the Waves Central window is showing up.

**Comment by PietJankbal** [comment]
Hi,
>I somehow solved the issue, but have no clue how. I installed the PowerShell myself and now at least the Waves Central window is showing up.

ok, then i close this issue
