### ISSUE TITLE
Waves Central Errors Out Before Opening

### ISSUE THREAD

**Issue by ghost** [PietJankbal/powershell-wrapper-for-wine#24]
After installing powershell, Waves Central still does not start. Here's what I did.  

```
wine install_pwshwrapper.exe
wine powershell
```
this error appeared in the terminal output: `02ec:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x7fa8f0e52930 `
But the powershell neverleless opened up with "Press Enter or Esc to exit"

then 
```
cd ~/.local/share/wineprefixes/waves/drive_c/Program\ Files/Waves\ Central
wine "Waves Central.exe"
```

Waves Central does not open and that results in the following error from wine:
[err_wine_waves_central_exe.txt](https://github.com/PietJankbal/powershell-wrapper-for-wine/files/11503642/err_wine_waves_central_exe.txt)

I am running AV Linux (Based on MX Linux, based on Debian)

**Comment by PietJankbal** [comment]
Hi ,

This looks like a crash inside waves central so it's likely a wine-bug. What version of Waves are you trying to run? And what wine version did you use?

**Comment by ghost** [comment]
After more experimentation, I found that I needed to run the installer with wine 8.5 (staging). 8.8 (staging) caused this error. Thanks for your help!
