### ISSUE TITLE
How to do an unattended install?

### ISSUE THREAD

**Issue by brunoais** [PietJankbal/powershell-wrapper-for-wine#25]
I'm trying to setup a packaged program and for that purpose, it would be very productive if the installation was unattended.

The way this works now, it requires a human to press the OK when running the program and to close the terminal after setup.

May you please add an option for this to run unattended?

**Comment by PietJankbal** [comment]
Hi, I have removed the MessageBox as it was not very useful anyway. So now you don't have to press 'OK'. 

Closing this issue, feel free to reopen if issue is not resolved the way you meant.

Regards

**Comment by brunoais** [comment]
Yes. Thank you. That is enough for unattended install. I run like this now:

```
set -e
wget https://github.com/PietJankbal/powershell-wrapper-for-wine/raw/master/install_pwshwrapper.exe
wine install_pwshwrapper.exe
wine powershell -noni -c 'echo "done"'
```
Feel free to add that to the README.md.
Thank you!

**Comment by PietJankbal** [comment]
Thanks for the tip! I've added it to the README
