### ISSUE TITLE
Merging a fork that has diverged a bit

### ISSUE THREAD

**Issue by ProjectSynchro** [PietJankbal/powershell-wrapper-for-wine#28]
Heyo, I forked this project: https://github.com/ProjectSynchro/powershell-wrapper-for-wine and was curious if you wanted to merge in some of my work.

This would include CI and CD for some releases for the wrapper, a workaround for ConEmu (at the cost of colour in powershell)
Winetricks verbs for installation, and a few formatting changes to make the code more readable (to me at least).

In theory if we get all this work in the right place, we could try and upstream this wrapper to be included in winetricks as a verb (would make this trivial for users to install). 

Let me know what you think.

**Comment by PietJankbal** [comment]
Hi there,

Sorry for the late reply but I've been really busy and still am atm.

Good job to try include this into winetricks so go ahead! I think it's best you try get your fork into winetricks, as I want to keep ConEmu in my own repository. My wrapper is basically meant for Waves Central, so i really want to keep it here as it is now.

I had a quick look at your fork and just 2  remarks:

- I think you removed a line too much here:
// Handle pipeline for reading from stdin
    if (read_from_stdin) {
        // Handle pipe
        if (GetFileType(GetStdHandle(STD_INPUT_HANDLE)) != FILE_TYPE_CHAR) {
            if (!wcscmp(argv[argc - 1], L"-") && _wcsnicmp(argv[argc - 2], L"-c", 2)) {
                wcscat(cmdlineW, L" -c ");

This part won't read from stdin anymore so this won't work anymore.  The following line takes care of reading from stdin and is not present anymore in your code:
while( fgets(line, 4096, stdin) != NULL ) { mbstowcs(defline, line, 4096); wcscat(cmdlineW, defline);}

Check with e.g. 'get-date' | powershell.exe

- Could you put the remark back from where the replace_smart function was taken?  So:
 /* Following function taken from https://creativeandcritical.net/downloads/replacebench.c which is in public domain; Credits to the there mentioned authors*/ 

Regards

**Comment by ProjectSynchro** [comment]
Hey! 

Thanks for the input, I have added back the remark about replace_smart. 
I also fixed the issue you noted about piped inputs not working, whoops, let my automated tools get the best of me there.

I'll close this since you'd like to keep your repo the same as it is at the moment.

Cheers
