### ISSUE TITLE
wine powershell won't start

### ISSUE THREAD

**Issue by perlindgren** [PietJankbal/powershell-wrapper-for-wine#3]
Hi

I'm under arch, and latest wine 
wine --version
wine-5.20

I ran the scripts to have powershell installed.

```shell
>wine powershell 
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

0024:fixme:powershell:wmain stub: L"C:\\windows\\system32\\powershell.exe"

windows/system32/WindowsPowerShell
❯ 0034:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 6
0034:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
0034:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 6
```
It continues to give these errors until I press enter. Seems at that point powershell is not really running.

I also tried this
```shell
> wine pwsh
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

0034:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 6
0034:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
00f4:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000029EF98
00f4:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0000000000B367E0, 0000000000E2A730, 0000000000E2A730) stub.
...
0034:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
00f4:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

0138:fixme:ntdll:EtwEventRegister ({74af9f20-af6a-5582-9382-f21f674fb271}, 0000000000EB3544, 0000000000000000, 00000000013DB388) stub.
0138:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000013DB330, 37) stub
...
```
It continues to output trace data, but if I enter a command (e.g., ls) powershell outputs a directory listing. So to some extent this works (just these annoying trace messages).

On the other hand, if I run the file downloaded dircectly.

```
❯ pwd
/home/pln/.wine/drive_c/windows/system32/WindowsPowerShell/v1.0
>./powershell
```
Then it starts a new window (under wine). 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4089704/97784844-ac570200-1ba1-11eb-9a5c-710eeae9faa2.png">

When I try installing the waves installer I get a splash screen with an error message (the same an in the other issue above). I have winecfg as win7 by default.

Any ideas what is happening here? (I'm not sure what to expect as I have not used powershell under windows before, besides perhaps indirectly without knowing.)
/Per

**Comment by PietJankbal** [comment]
Hi, try cd into the directory where Waves Central is e.g.  --> cd ~/.wine/drive_c/Program\ Files/Waves\ Central/ 

Then try start start again-->   wine  Waves\ Central.exe

Does that help? Might also need 'winetricks arial' and /or dxvk151 (?)

When the installer tries start Waves it doesn`t work, I don`t know why ...

**Comment by perlindgren** [comment]
I think I might have had some bad leftovers from previous attempts to install powershell. So I unistalled it (wine uninstaller). Then I started powershell from 
`~/.wine/drive_c/windows/system32/WindowsPowerShell/v1.0/powershell.exe`

It downloaded the powershell as expected. Now I can launch powershell by `wine powershell` (that did not work before). 

EDIT: Well it worked once. Trying to launch powershell now results in:
❯ wine powershell
0024:fixme:powershell:wmain stub: L"C:\\windows\\system32\\powershell.exe"

and nothing happens.

In any case:

First time trying to start the "Waves Central" application I got a:
0238:err:module:open_builtin_file failed to load .so lib "/usr/lib/wine/d3d12.dll.so"

Any idea what to do about that? (I'm running wine as win7 at the moment.)

(So there might be multiple unrelated problems here...)

**Comment by PietJankbal** [comment]
Maybe missing vulkan support/old graphics card/driver?

What happens if you run -->  wine Waves\ Central.exe --disable-gpu

**Comment by perlindgren** [comment]
Now it started, thanks a bunch.

Out of curiosity, do you also have the behaviour that
>wine powershell

Just returns.
While

>wine pwsh

Gets you a pwsh, but not a new windows window.

**Comment by PietJankbal** [comment]
wine powershell does actually do (inside the code) wine ConEmu64.exe pwsh.exe. That`s why a new console window is created.

If you do "wine start pwsh.exe" or "wine ConEmu64.exe pwsh.exe" then you also get the "new window"

Regards

**Comment by PietJankbal** [comment]
I close this one, please report remaining issues in new bugreports
