### ISSUE TITLE
Debian Buster

### ISSUE THREAD

**Issue by osxmidi** [PietJankbal/powershell-wrapper-for-wine#5]
l get this on MX Linux (Debian Buster) Wine-Staging 6 rc1

015c:err:seh:check_bpf_jit_enable BPF JIT is not enabled in the kernel, enable it to reduce syscall emulation overhead.
Downloading File From: https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-
7.0.3-win-x64.msi, To: PowerShell-7.0.3-win-x64.msi
0154:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0160:fixme:wininet:set_cookie secure not handled
0160:fixme:wininet:set_cookie Unknown additional option L"SameSite=Lax"
0160:fixme:wininet:set_cookie secure not handled
0160:fixme:wininet:set_cookie Unknown additional option L"SameSite=Lax"
0160:fixme:wininet:set_cookie secure not handled
0160:fixme:wininet:set_cookie Unknown additional option L"SameSite=Lax"
0154:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3
File Successfully Downloaded
0184:fixme:file:NtLockFile I/O completion on lock not implemented yet
0184:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0184:err:mscoree:LoadLibraryShim error reading registry key for installroot
0184:err:mscoree:LoadLibraryShim error reading registry key for installroot
0184:err:mscoree:LoadLibraryShim error reading registry key for installroot
0184:err:mscoree:LoadLibraryShim error reading registry key for installroot
0184:err:msi:ACTION_InstallFiles compressed file wasn't installed (L"fil000420A1263645A49F163FBF3C249FA6")
0184:err:msi:execute_script Execution of script 0 halted; action L"InstallFiles" returned 1603
0184:err:msi:ITERATE_Actions Execution halted, action L"InstallFinalize" returned 1603
0154:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
File Successfully Downloaded
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
0198:fixme:exec:SHELL_execute flags ignored: 0x00000100
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

FIXME Waiting for 5 secs to finish things, otherwise it just fails on first run...

old command line is

new command line is

Can't recognise 'c:\ConEmu\ConEmu.exe -resetdefault -run pwsh.exe ' as an internal or external comma
nd, or batch script.
osuser@mx:~/Downloads/powershell-wrapper-for-wine-master
$ ConEmu
bash: ConEmu: command not found

**Comment by PietJankbal** [comment]
hI, sorry for late reply. Is this on a complete new wineprefix?  Also , could you check if the folders c:\\Program Files\\Powershell\\7\\ and c:\\Conemu are present and populated with files?

Regards

**Comment by PietJankbal** [comment]
Also, please make sure windows 7 or 8 is selected in winecfg while trying install. 

Regards

**Comment by PietJankbal** [comment]
As there`s no response I close this one
