### ISSUE TITLE
Wine 6.5 and most recent version of Waves Central Permissions Issue

### ISSUE THREAD

**Issue by ghost** [PietJankbal/powershell-wrapper-for-wine#8]
I'm having the same permissions issue that was documented here https://github.com/PietJankbal/powershell-wrapper-for-wine/issues/4

The Good: The installation still works after following all the steps. Meaning, we can run wine64 waves.exe (or whatever the executable was named). Even though it crashes and tells us it's not installed. Because... proprietary.

The Bad: After manually modifying the ACL permissions in powershell as per https://github.com/PietJankbal/powershell-wrapper-for-wine/issues/4, it's still running a permissions issue. I'm really busy right now but on Thursday I'm going to check the logs like cshao06 did. However, I did try checking for the logs under drive_c/users/usernameApplication\ Data/Waves\ Audio/Waves\ Central/Logs/permissionFixer/ and I couldn't find the log file. 

The Ugly: This is sort of ridiculous. Why did they change their program to become worse? Why are they passing arguments into powershell? Passing commands into the shell of an OS from a program is bad practice. It can do weird things to the threading, it's a security vulnerability, and in general just reflects a dis unified and bloated program.  A multi million dollar (at least) company like waves should be able to hire competent programmers. Why are they writing this in electron.js? We do not need more bloated programs. I do not need to run a local web server to access DRM protected plugins. They should be ashamed that I need to hold the hand of their immobile script and manually change the ACL permissions because with all of their money they are still struggling to program powershell scripts.

 Some things I'm going to try and I'll update this issue:

1.  Downgrading to Wine 6.4
2. Thoroughly searching on the file system for the logs directory (I tried last time and couldn't find anything)
3. Reading the logs and checking if there are additional ACL permissions that need to be changed

I apologize for posting this issue before trying those three things. But I'm quite busy as it's the end of the semester, and I wanted to go ahead and note this ahead of time to see if anyone has any suggestions. I'll update this before or on Thursday April 8

**Comment by PietJankbal** [comment]
Hi koyafish,

Please try wine-staging 6.5 instead of vanilla-wine and see if that "fixes" the permission issue. There`s a patch in Staging that i believe should fix this permission-issue. If it doesn`t, please let me know; if it does, also please let me know ;)

**Comment by ghost** [comment]
Thank you! That worked. For anyone else who is reading this and needs help, here's what I did on ubuntu

 apt get install wine-staging
 apt get --install-recommends winehq-staging
apt get autoremove (you should remove old versions of wine, this should work)
winecfg (check if 'staging' is a tab to check if you've replaced vanilla wine with wine staging correctly)


I'll open another issue if something else occurs at a different point in the usage of the application. I appreciate you work, thank you for helping out
