### ISSUE TITLE
PowerShell is downloaded every time it gets run

### ISSUE THREAD

**Issue by tobias-kuendig** [PietJankbal/powershell-wrapper-for-wine#9]
If i run Powershell directly in Wine, it gets always downloaded again. Do you have any advice on how to fix this?

```bash
$ wine powershell
Downloading File From: https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x64.msi, To: PowerShell-7.0.3-win-x64.msi

0784:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0784:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3
File Successfully Downloaded

07a0:fixme:exec:SHELL_execute flags ignored: 0x00000100
07a8:fixme:file:NtLockFile I/O completion on lock not implemented yet
07a8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
07a8:err:msi:ITERATE_Actions Execution halted, action L"LaunchConditions" returned 1603
0784:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
File Successfully Downloaded

FIXME Waiting for 5 secs to finish things, otherwise it just fails on first run...


old command line is

new command line is
```

**Comment by PietJankbal** [comment]
It says 

07a8:err:msi:ITERATE_Actions Execution halted, action L"LaunchConditions" returned 1603

so it fails to install. Which wine-version do you run?

**Comment by tobias-kuendig** [comment]
Thank you for your reply. This happens on `wine-6.9 (Staging)`, but I also had the problem on 6.0 stable

**Comment by PietJankbal** [comment]
Hmm, strange then. Could you try (in some other prefix) to run the installer manually and see what happens?
https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x64.msi


 Because

**Comment by tobias-kuendig** [comment]
I did run your installer in a separate prefix and PowerShell started just fine (after the initial download). Looks like something in my defualt wine prefix is messed up!

Thank you for your help!

**Comment by tobias-kuendig** [comment]
Looks like something else has installed PowerShell components in my default wine prefix, but those did not work correctly. I simply remove everything named "PowerShell" from the prefix and now was able to get it running:


```bash
find ~/.wine -name PowerShell -exec rm -rf "{}" ';'
```

**Comment by PietJankbal** [comment]
Ok, good that it worked. 
As a guess I would say that some wine-version (i think <5.18????? left a fake powershell.exe in system32/syswow64. I also had that some time, when you run a wine-version before  5.*  it creates a placeholder in the ( wronng) directory system32/syswow64.
Regards
